name: C Test

on: 
  workflow_dispatch:
      
jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Change Directory
        run: Leetcode/eveluation/user_test.cpp
        
      - name: compile and run user_test.cpp
        run: |
          g++ user_test.cpp -o user_test  #编译用户的代码文件
          
          ./user_test #运行用户的测试代码
