name: C Test

on: 
  push:
    branches:
      - main  # 或其他默认分支名称

jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: compile and run user_test.cpp
        run: |
          g++ .github/evaluation/evaluation_105/user_test.cpp -o user_test.exe
          
          ./.github/evaluation/evaluation_105/user_test.exe
